image: node:latest

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules
    
stages:
  - install
  - build
    
install:
  stage: install
  script:
    - npm ci

branch_build:
  stage: build
  only:
    - master
  script: 
  - git fetch --force origin "master:remotes/origin/master"
  - npm run ci:build

