image: node:latest

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    
stages:
  - build

build:
  stage: build
  script: 
  - git fetch origin master:refs/remotes/origin/master
  - npm ci
  - npm run ci:build