image: node:latest

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    
stages:
  - checkout
  - install
  - build

checkout:
  stage: checkout
  script: 
    - git fetch origin master
    
install:
  stage: install
  script:
    - npm ci

branch_build:
  stage: build
  only:
    - master
  script: 
  - npm run affected:build -- --all

