image: node:latest

before_script:
  - npm ci --silent

stages:
  - checkout
  - build

checkout_job:
  stage: checkout
  script: git fetch origin master:refs/remotes/origin/master
build_job:
  stage: build
  script: npm run ci:build