image: node:latest

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress

before_script:
  - npm ci --silent

stages:
  - checkout
  - build

checkout_job:
  stage: checkout
  script: git fetch origin master:refs/remotes/origin/master
build_job:
  stage: build
  script: npm run ci:build