version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Installing dependencies
          command: 'npm ci'
      - run:
          name: Building app
          command: 'npm run ci:build'
      - run:
          name: Deploy app
          command: 'npm run ci:deploy'
workflows:
  version: 2
  build:
    jobs:
      - build