version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}